plugins {
    id "architectury-plugin" version "3.4.162"
    id "dev.architectury.loom" version "1.9.436" apply false
    id "com.gradleup.shadow" version "8.3.10" apply false
}

architectury {
    minecraft = project.minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"
    apply plugin: "architectury-plugin"

    loom {
        silentMojangMappingsLicense()
    }

    base {
        archivesName = project.mod_id
    }

    dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings loom.layered() {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${project.parchment_minecraft_version}:${project.parchment_mappings_version}@zip")
        }
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"

    version = project.mod_version
    group = project.mod_group_id

    repositories {
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.parchmentmc.org/" }
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.shedaniel.me/" }
        mavenCentral()
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 21
    }

    java {
        withSourcesJar()
    }
}
