pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.neoforged.net/releases/" }
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'mmdsync'

include("common")
include("fabric")
include("neoforge")

// 引入核心 mod 项目，以便 Mixin 编译
// includeBuild("MC-MMD-rust") {
//     dependencySubstitution {
//         substitute module('com.shiroha233.mmdskin:mmdskin-common') using project(':common')
//     }
// }

