modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
    config="mmdsync-common.mixins.json"
    side="CLIENT"

[[mixins]]
    config="mmdsync-neoforge.mixins.json"
    side="CLIENT"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="architectury"
    type="required"
    versionRange="[13.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mmdskin"
    type="required"
    versionRange="[1.0,)"
    ordering="AFTER"
    side="CLIENT"
